---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: directus-autoscaling-hpa
  namespace: default
  labels:
    app.kubernetes.io/name: directus
    app.kubernetes.io/instance: directus-autoscaling
    app.kubernetes.io/component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: directus-autoscaling  # This should match the Directus deployment name
  minReplicas: 2
  maxReplicas: 10
  
  # Define multiple metrics for scaling decisions
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Advanced scaling behavior to prevent flapping
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60              # Max 2 pods per minute
      - type: Percent
        value: 50
        periodSeconds: 60              # Max 50% increase per minute
      selectPolicy: Min                # Use the more conservative policy
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120             # Max 1 pod every 2 minutes
      - type: Percent
        value: 10
        periodSeconds: 60              # Max 10% decrease per minute
      selectPolicy: Min                # Use the more conservative policy 