apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yaml
  - redis.yaml
  - storage.yaml
  - hpa.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: directus-autoscaling
  deployment.type: production 