---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-uploads-pvc
  namespace: default
  labels:
    app: directus
    component: storage
spec:
  accessModes:
    - ReadWriteMany  # ReadWriteMany for shared access across multiple pods
  resources:
    requests:
      storage: 20Gi
  # Uncomment and modify based on your storage class
  # storageClassName: fast-ssd 