apiVersion: directus.example.com/v1
kind: Directus
metadata:
  name: simple-directus
  namespace: default
spec:
  # Minimal configuration for testing
  replicaCount: 1
  
  image:
    repository: directus/directus
    tag: "latest"
  
  adminEmail: "admin@test.com"
  
  # Create service account
  serviceAccount:
    create: true
  
  service:
    type: ClusterIP
    port: 80
  
  # Use SQLite for simple testing (no external database required)
  database:
    engine: sqlite
  
  # Disable Redis for simplicity
  redis:
    enabled: false
  
  # Enable basic probes
  enableLivenessProbe: true
  enableReadinessProbe: true
  
  # Create application secrets
  createApplicationSecret: true
  
  # Basic resource limits
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi 